### ISSUE TITLE
Make sure we develope against the latest dev.version (Juicebox 8.x-2.0-beta4)

### ISSUE THREAD

**Issue by D4KO** [fkelly12054/juicebox-kelly#10]
We're developing against old dev.version of Juicebox 8.x-2.0-beta2
It looks like some work has been already done (t() function, some dependency injection) in new dev.versions.
Checkout here 
https://www.drupal.org/project/juicebox/releases/8.x-2.0-beta4

I think we should develop against the latest Juicebox dev. version to avoid troubles in the future.
That means we should implement or merge somehohow those offical changes into our fork.
Needs discussion.

**Comment by D4KO** [comment]
Well, I did some more quick research, comparing https://git.drupalcode.org/project/juicebox/-/commits/8.x-2.x against our master.
Our master includes changes in the last Juicebox dev.commit #3175767. Good news! Looks like we're up-to-date.
We differs in handling external library loading, but it was said it's have a purpose, right?

I believe this issue can be soon closed. Just wanna make sure we have every official changes implemented (except for ext.library loading)

**Comment by fkelly12054** [comment]
I think we are working against 8.x-2.dev.  Yes, the initial purpose of the work I was doing was to remove external library dependency (actually this would be more precisely stated as remove the dependency on the contrib module libraries and built a $library array completely within the Juicebox module).  It is always possible that we may uncover a bug or three in how I did that but it's been in place for more than a month.  At any rate the code on this (fkelly) git hub repository now incorporates hundreds of changes for coding standards as well as the dependency injection changes and other coding standards changes you (DK40) have made in the last few days.  There is no going back from this ... at least not with me onboard the train.
